### ISSUE TITLE
Use Noto font on the login page

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-core#6382]
**What feature do you want to improve?**
Currently we use `"Helvetica Neue",Helvetica,Arial,sans-serif` as the font on the login page. This is inconsistent with the Noto San used in the add, and in some languages and devices could end up being unable to render the characters.

**Describe the improvement you'd like**
Switch to Noto Sans. It is already cached in the service worker so should just work with no additional overheads. eg:

```css
@font-face {
  font-family: 'Noto';
  src: url(/fonts/NotoSans-Regular.ttf) format("truetype");
}
body, input {
  font-family: Noto, sans-serif;
}
```

**Describe alternatives you've considered**
Leaving it as is - it works ok and I'm probably the only one who's noticed...
