### ISSUE TITLE
Report verification does not do proper minification before saving

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-core#6802]
**Describe the bug**
Instead of updating the minified report with the verification information, the report is saved with a fully hydrated patient. 

**To Reproduce**
1. Open a report that has a patient. Check the report json and make sure the report is minified (the contact fields are not hydrated and there is no `patient` property). 
2. Verify this report (verification type is irrelevant).
3. Check the report json again and observe that it has a fully hydrated `patient` property.

**Expected behavior**
Reports should always be minified before saving.

**Environment**
- Instance: gamma.dev
- App: webapp
- Version: 3.10

**Comment by dianabarsan** [comment]
When working on this, we should update the e2e test that does report verification to check the report's json.

**Comment by garethbowen** [comment]
Delayed to 3.12.0 to speed up 3.11.0 release.

**Comment by m5r** [comment]
This is ready for AT on branch `6802-report-verification-wont-minify`  
[PR link](https://github.com/medic/cht-core/pull/7417)

**Comment by lorerod** [comment]
Note: This [PR](https://github.com/medic/cht-core/pull/7417) has conflicts that must be resolved.

**Reproducible on Master**
- After verifying the report, JSON has a fully hydrated patient property. 
```yaml
{
    "_id": "504d93f3-3c27-41ea-9897-f1f3d2fa8c9d",
    "_rev": "2-0986ba5258c4e4c237561e2e94cb2457",
    "form": "pnc_danger_sign_follow_up_mother",
    "type": "data_record",
    "content_type": "xml",
    "reported_date": 1640875067629,
    "contact": {
        "_id": "42067b5c-0a90-4944-9f54-a35862351111",
        "parent": {
            "_id": "ac632adb-5435-4d4e-90cb-85292d9def11"
        }
    },
    "from": "",
    "hidden_fields": [
        "patient_age_in_years",
        "patient_uuid",
        "patient_id",
        "patient_name",
        "patient_short_name",
        "patient_short_name_start",
        "t_danger_signs_referral_follow_up_date",
        "t_danger_signs_referral_follow_up",
        "danger_signs.danger_signs_question_note",
        "danger_signs.r_danger_sign_present",
        "danger_signs.congratulate_no_ds_note",
        "danger_signs.custom_translations",
        "data",
        "meta",
        "inputs"
    ],
    "fields": {
        "inputs": {
            "meta": {
                "location": {
                    "lat": "",
                    "long": "",
                    "error": "",
                    "message": ""
                },
                "deprecatedID": ""
            },
            "source": "user",
            "source_id": "",
            "delivery_uuid": "",
            "contact": {
                "_id": "9b49a5be-4a7e-4b52-909f-f14be2e2f422",
                "name": "Mama",
                "short_name": "",
                "patient_id": "89424",
                "date_of_birth": "1999-12-30",
                "sex": "female",
                "parent": {
                    "_id": "ac632adb-5435-4d4e-90cb-85292d9def11",
                    "parent": {
                        "contact": {
                            "chw_name": "",
                            "phone": ""
                        }
                    }
                }
            }
        },
        "patient_age_in_years": "22",
        "patient_uuid": "9b49a5be-4a7e-4b52-909f-f14be2e2f422",
        "patient_id": "89424",
        "patient_name": "Mama",
        "patient_short_name": "the woman",
        "patient_short_name_start": "The woman",
        "t_danger_signs_referral_follow_up_date": "2022-01-02T00:00:00.000-03:00",
        "t_danger_signs_referral_follow_up": "no",
        "danger_signs": {
            "visit_confirm": "yes",
            "danger_sign_present": "no",
            "danger_signs_question_note": "",
            "fever": "no",
            "severe_headache": "no",
            "vaginal_bleeding": "no",
            "vaginal_discharge": "no",
            "convulsion": "no",
            "r_danger_sign_present": "no",
            "congratulate_no_ds_note": "",
            "custom_translations": {
                "custom_woman_label_translator": "woman",
                "custom_woman_label": "the woman",
                "custom_woman_start_label_translator": "woman-start",
                "custom_woman_start_label": "The woman"
            }
        },
        "data": {
            "__visited_hf": "yes",
            "__still_experiencing_danger_sign": "no",
            "__fever": "no",
            "__severe_headache": "no",
            "__vaginal_bleeding": "no",
            "__vaginal_discharge": "no",
            "__convulsions": "no",
            "__has_danger_sign": "no",
            "meta": {
                "__patient_uuid": "9b49a5be-4a7e-4b52-909f-f14be2e2f422",
                "__patient_id": "89424",
                "__household_uuid": "ac632adb-5435-4d4e-90cb-85292d9def11",
                "__source": "user",
                "__source_id": "",
                "__delivery_uuid": ""
            }
        },
        "meta": {
            "instanceID": "uuid:e153197a-7a59-46e1-a3ae-76092c1746db"
        }
    },
    "geolocation_log": [
        {
            "timestamp": 1640875067640,
            "recording": {
                "latitude": -25.33765139811435,
                "longitude": -57.62579176936458,
                "altitude": 92.75130462646484,
                "accuracy": 65,
                "altitudeAccuracy": 23.763031005859375,
                "heading": null,
                "speed": null
            }
        }
    ],
    "geolocation": {
        "latitude": -25.33765139811435,
        "longitude": -57.62579176936458,
        "altitude": 92.75130462646484,
        "accuracy": 65,
        "altitudeAccuracy": 23.763031005859375,
        "heading": null,
        "speed": null
    },
    "patient": {
        "parent": {
            "parent": "",
            "type": "district_hospital",
            "is_name_generated": "true",
            "name": "lorena's Health Facility",
            "external_id": "",
            "notes": "",
            "contact": {
                "parent": {
                    "_id": "ac632adb-5435-4d4e-90cb-85292d9def11"
                },
                "type": "person",
                "name": "maurizio",
                "short_name": "",
                "date_of_birth": "1979-12-30",
                "date_of_birth_method": "approx",
                "ephemeral_dob": {
                    "age_label": "",
                    "age_years": "42",
                    "age_months": "",
                    "dob_method": "approx",
                    "ephemeral_months": "12",
                    "ephemeral_years": "1979",
                    "dob_approx": "1979-12-30",
                    "dob_raw": "1979-12-30",
                    "dob_iso": "1979-12-30"
                },
                "sex": "male",
                "phone": "",
                "phone_alternate": "",
                "role": "chw_supervisor",
                "external_id": "",
                "notes": "",
                "meta": {
                    "created_by": "medic",
                    "created_by_person_uuid": "",
                    "created_by_place_uuid": ""
                },
                "reported_date": 1640873363942,
                "patient_id": "83598",
                "_id": "d4778686-b0fe-4486-b666-2ae4a0048c65",
                "_rev": "2-2c4e8e31069722c578b34ae5c8d71774"
            },
            "geolocation": "",
            "meta": {
                "created_by": "medic",
                "created_by_person_uuid": "",
                "created_by_place_uuid": ""
            },
            "reported_date": 1640791569281,
            "place_id": "30120",
            "_id": "ac632adb-5435-4d4e-90cb-85292d9def11",
            "_rev": "4-bb00b3554fede73515f7ab065481e335"
        },
        "type": "person",
        "name": "Mama",
        "short_name": "",
        "date_of_birth": "1999-12-30",
        "date_of_birth_method": "approx",
        "ephemeral_dob": {
            "age_label": "",
            "age_years": "22",
            "age_months": "",
            "dob_method": "approx",
            "ephemeral_months": "12",
            "ephemeral_years": "1999",
            "dob_approx": "1999-12-30",
            "dob_raw": "1999-12-30",
            "dob_iso": "1999-12-30"
        },
        "sex": "female",
        "phone": "",
        "phone_alternate": "",
        "role": "patient",
        "external_id": "",
        "notes": "",
        "meta": {
            "created_by": "lorena",
            "created_by_person_uuid": "42067b5c-0a90-4944-9f54-a35862351111",
            "created_by_place_uuid": "ac632adb-5435-4d4e-90cb-85292d9def11"
        },
        "reported_date": 1640875001754,
        "patient_id": "89424",
        "_id": "9b49a5be-4a7e-4b52-909f-f14be2e2f422",
        "_rev": "2-8c021419e934724bf189e1aaf3589b85"
    },
    "verified": true,
    "verified_date": 1640875348369,
    "_attachments": {
        "content": {
            "content_type": "application/xml",
            "revpos": 1,
            "digest": "md5-+opPB59S2k23SqbM5ik7Kg==",
            "length": 3837,
            "stub": true
        }
    }
}
```

**Fixed on Branch**
- After verifying the report, the report is minified (the contact fields are not hydrated and there is no patient property).
```yaml
{
    "_id": "9026b993-c11b-4deb-829a-c13260b11a06",
    "_rev": "2-288e784c3802d1bebc46275c7df73bc8",
    "form": "pnc_danger_sign_follow_up_mother",
    "type": "data_record",
    "content_type": "xml",
    "reported_date": 1640875770466,
    "contact": {
        "_id": "42067b5c-0a90-4944-9f54-a35862351111",
        "parent": {
            "_id": "ac632adb-5435-4d4e-90cb-85292d9def11"
        }
    },
    "from": "",
    "hidden_fields": [
        "patient_age_in_years",
        "patient_uuid",
        "patient_id",
        "patient_name",
        "patient_short_name",
        "patient_short_name_start",
        "t_danger_signs_referral_follow_up_date",
        "t_danger_signs_referral_follow_up",
        "danger_signs.danger_signs_question_note",
        "danger_signs.r_danger_sign_present",
        "danger_signs.congratulate_no_ds_note",
        "danger_signs.custom_translations",
        "data",
        "meta"
    ],
    "fields": {
        "inputs": {
            "meta": {
                "location": {
                    "lat": "",
                    "long": "",
                    "error": "",
                    "message": ""
                },
                "deprecatedID": ""
            },
            "source": "user",
            "source_id": "",
            "delivery_uuid": "",
            "contact": {
                "_id": "9b49a5be-4a7e-4b52-909f-f14be2e2f422",
                "name": "Mama",
                "short_name": "",
                "patient_id": "89424",
                "date_of_birth": "1999-12-30",
                "sex": "female",
                "parent": {
                    "_id": "ac632adb-5435-4d4e-90cb-85292d9def11",
                    "parent": {
                        "contact": {
                            "chw_name": "",
                            "phone": ""
                        }
                    }
                }
            }
        },
        "patient_age_in_years": "22",
        "patient_uuid": "9b49a5be-4a7e-4b52-909f-f14be2e2f422",
        "patient_id": "89424",
        "patient_name": "Mama",
        "patient_short_name": "the woman",
        "patient_short_name_start": "The woman",
        "t_danger_signs_referral_follow_up_date": "2022-01-02T00:00:00.000-03:00",
        "t_danger_signs_referral_follow_up": "no",
        "danger_signs": {
            "visit_confirm": "yes",
            "danger_sign_present": "no",
            "danger_signs_question_note": "",
            "fever": "no",
            "severe_headache": "no",
            "vaginal_bleeding": "no",
            "vaginal_discharge": "no",
            "convulsion": "no",
            "r_danger_sign_present": "no",
            "congratulate_no_ds_note": "",
            "custom_translations": {
                "custom_woman_label_translator": "woman",
                "custom_woman_label": "the woman",
                "custom_woman_start_label_translator": "woman-start",
                "custom_woman_start_label": "The woman"
            }
        },
        "data": {
            "__visited_hf": "yes",
            "__still_experiencing_danger_sign": "no",
            "__fever": "no",
            "__severe_headache": "no",
            "__vaginal_bleeding": "no",
            "__vaginal_discharge": "no",
            "__convulsions": "no",
            "__has_danger_sign": "no",
            "meta": {
                "__patient_uuid": "9b49a5be-4a7e-4b52-909f-f14be2e2f422",
                "__patient_id": "89424",
                "__household_uuid": "ac632adb-5435-4d4e-90cb-85292d9def11",
                "__source": "user",
                "__source_id": "",
                "__delivery_uuid": ""
            }
        },
        "meta": {
            "instanceID": "uuid:e769fbdf-0a26-4b6c-ae61-3dae7c10e13c"
        }
    },
    "geolocation_log": [
        {
            "timestamp": 1640875770478,
            "recording": {
                "latitude": -25.33754681213551,
                "longitude": -57.62604640504012,
                "altitude": 92.66712188720703,
                "accuracy": 65,
                "altitudeAccuracy": 29.349689483642578,
                "heading": null,
                "speed": null
            }
        }
    ],
    "geolocation": {
        "latitude": -25.33754681213551,
        "longitude": -57.62604640504012,
        "altitude": 92.66712188720703,
        "accuracy": 65,
        "altitudeAccuracy": 29.349689483642578,
        "heading": null,
        "speed": null
    },
    "verified": true,
    "verified_date": 1640876112278,
    "_attachments": {
        "content": {
            "content_type": "application/xml",
            "revpos": 1,
            "digest": "md5-UJczOe2fo8jOSYw9L3kD7w==",
            "length": 3837,
            "stub": true
        }
    }
}
```
