### ISSUE TITLE
GitHub Action failing because of change to docker-compose location/contents

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#7206]
**Describe the issue**
A [commit back in April](https://github.com/medic/cht-infrastructure/commit/fbe1da566d2af664cf1e23588e2840655420fd50#diff-38219779f5fcc301ef54b6a95ad7287532c7f0d20619c83aebc6c6034b5e7b72R24-R25) moved the location of the `docker-compose.yml` file used in the `medic-infrastracture` repo, specifically the `self-hosting/prepare-system/ubuntu/prepare.sh` script.  The new `docker-compose.yml` file does not allow for `DOCKER_COUCHDB_ADMIN_PASSWORD` to be set in an environment variable.   As such, CI scripts now fail because they can not login to complete testing.  

**Describe the improvement you'd like**
We should likely enable the new `docker-compose.yml` to support the old functionality. The [original file is here](https://github.com/medic/cht-infrastructure/commit/883761e36a3b989c6c0711c0622fa413823a010b#diff-0fd6a68424d0e206753100aebe402f451f0026a3b8c28b9598127046fd70d8be) with this as stanza for `medic-os` container:

```yml
services:
  medic-os:
    container_name: medic-os
    image: medicmobile/medic-os:cht-3.9.0-rc.2
    volumes:
      - medic-data:/srv
    ports:
     - 80:80
     - 443:443
    working_dir: /srv
    depends_on:
      - haproxy
    networks:
      - medic-net
    environment:
      - DOCKER_NETWORK_NAME=haproxy
      - DOCKER_COUCHDB_ADMIN_PASSWORD=$DOCKER_COUCHDB_ADMIN_PASSWORD
```

Where as the one in `cht-core`, now being used by CI, looks like this: 

```yml
services:
  medic-os:
    container_name: medic-os
    image: medicmobile/medic-os:cht-3.9.0-rc.2
    volumes:
      - medic-data:/srv
    ports:
     - 80:80
     - 443:443
    working_dir: /srv
    depends_on:
      - haproxy
    networks:
      - medic-net
    environment:
      - DOCKER_NETWORK_NAME=haproxy
      - DOCKER_COUCHDB_ADMIN_PASSWORD=password
```

**Describe alternatives you've considered**
Change the CI script to use the hard coded password in the new `docker-compose.yml` file.
