### ISSUE TITLE
CHT deploy script error: upgrade-service image referenced incorrectly

### ISSUE THREAD

**Issue by 1yuv** [medic/cht-core#9077]
Deploying with latest (`master`) cht-script results in incorrectly tagged pod and the service image is incorrect. 

**Steps to replicate:**
1. Check out current master
2. Create values.yaml with this [document reference
](https://docs.communityhealthtoolkit.org/contribute/code/core/deploy-on-eks/#starting-and-stopping-aka-deleting)
3. Apply this with `./cht-deploy` script from `cht-core/scripts/deploy`. 
4. When it completes applying, you get sucessful deployment. 
5. Check the status of pods. `upgrade-service` is failed at `InvalidImageName`.
   ```
   ➜  deploy git:(master) ✗ k -n yuvraj-dev get po                                       
   NAME                                       READY   STATUS             RESTARTS   AGE
   cht-api-5f99b5684f-5kl44                   1/1     Running            0          9m11s
   cht-couchdb-ffd46779-hlq72                 1/1     Running            0          9m11s
   cht-haproxy-8f66cb488-5vzkx                1/1     Running            0          9m11s
   cht-haproxy-healthcheck-7fbc585b9c-bznrx   1/1     Running            0          9m11s
   cht-sentinel-56f958f5b4-62htm              1/1     Running            0          9m11s
   upgrade-service-8c894c85c-7jbvl            0/1     InvalidImageName   0          9m11s
   ```

6. When you inspect the pod, you get detailed error: 
   ```
    state:
      waiting:
        message: 'Failed to apply default image tag "medicmobile/upgrade-service:medicmobile/upgrade-service:0.32":
          couldn''t parse image reference "medicmobile/upgrade-service:medicmobile/upgrade-service:0.32":
          invalid reference format'
        reason: InvalidImageName
   ```
7. The reason for this is image is being referenced incorectly. 
   ```yaml
   spec:
     containers:
     - env:
       - name: CHT_NAMESPACE
         valueFrom:
           fieldRef:
             apiVersion: v1
             fieldPath: metadata.namespace
       - name: CHT_DEPLOYMENT_NAME
         valueFrom:
           fieldRef:
             apiVersion: v1
             fieldPath: metadata.labels['cht.service']
       - name: UPGRADE_SERVICE_PORT
         value: "5008"
       image: medicmobile/upgrade-service:medicmobile/upgrade-service:0.32
       imagePullPolicy: IfNotPresent
       name: upgrade-service
   ```
