### ISSUE TITLE
Select an Identity Provider service for development

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-core#9737]
**Describe the issue**
In order to be able to actually be sure our code works for the SSO effort in #9735, we need to both have an instance that can be developed against, but also that can work in e2e tests. 

**Describe the improvement you'd like**
Find a solution that is either cloud based or docker based (or both?!) - but that is easy to set up and test against that provides just the most limited services we need.

**Describe alternatives you've considered**
Pay for an existing commercial service that one of the SSO squad members recommends.

**Comment by rmayore** [comment]
Yes @mrjones-plip

**Comment by raphaelkenyuri** [comment]
If we settle on a commercial service, is it possible to use Microsoft Azure AD.

CC @mrjones-plip @rmayore

**Comment by mrjones-plip** [comment]
@raphaelkenyuri - are you asking if the [MVP](https://github.com/medic/cht-core/issues/9735) will work on Azure AD (now called [Entra ID](https://www.microsoft.com/en-us/security/business/identity-access/microsoft-entra-id)  I see) or if the development effort can use Azure AD? 

In give my opinion on both, but will defer to @rmayore who's working on this ticket ;)
* the development environment should be as easy as possible to setup, and hopefully [support e2e testing](https://github.com/medic/cht-core/issues/9738) - this would rule out any commercial provider like  Azure AD.
* Conversely, we really want the end result  [MVP](https://github.com/medic/cht-core/issues/9735)  to be OIDC compliant, so I think it should work with any ID provider, including  Azure AD

**Comment by rmayore** [comment]
### Features to consider for testing

- Free and Open source.
- Docker based, meaning it can be installed locally and on the cloud
- Support for common protocols such as OIDC, Oauth 2.0, SAML
- Ability to run e2e tests
- IAM
- Single Sign-On
- Documentation and support

### Extras (Beyond Testing)

- Social Login
- User federation
- Multi-factor authentication

### Options Considered

1. Shibboleth - https://www.shibboleth.net/
2. Keycloak - https://www.keycloak.org/
3. OpenIAM - https://www.openiam.com/
4. Evolveum - https://evolveum.com/midpoint/#self-service
5. FusionAuth - https://fusionauth.io/
6. Apache Synocope - https://syncope.apache.org/
7. Auth0 - https://auth0.com/


### 1. Shibboleth
Free only for development and testing https://www.shibboleth.net/membership/consortium-membership-fees/
:heavy_check_mark: Open source
No native support for docker https://www.shibboleth.net/membership/consortium-membership-fees/
Support for SAML and OIDC
Possible to run e2e tests, not verified
IAM supported SSO supported 
Adequate documentation and support

### 2. Keycloak
Free
Open source
Native support for docker: Install [single container](https://www.keycloak.org/getting-started/getting-started-docker) for local dev work and [guides](https://www.keycloak.org/getting-started/getting-started-scaling-and-tuning) for HA setups on the cloud
Support for SAML and OIDC
E2E tests seems possible
IAM supported SSO supported 
Good documentation and support

### 3. OpenIAM
Current release paid, old releases paid
Open source
Complicated docker deployment https://docs.openiam.com/docs-4.2.1.3/installation/2-docker-installation
Support for SAML and OIDC
Couldn't get any mention of it online, or of someone who's tried it. If the docker install can be easily automated then e2e tests should be possible
IAM supported SSO supported 
Adequate documentation and support

### 4. Evolveum
Free, but paid for support, such as bug fixes, configuration consulting, and training
Open source
Native support for docker https://hub.docker.com/r/evolveum/midpoint/
Support for SAML and OIDC
E2e testing seems possible
IAM supported SSO supported 

Adequate documentation and support

### 5. FusionAuth
Not open-source
Didn't bother to check on the other features


### 6. Apache Synocope
Free
Open source
Good native docker support https://syncope.apache.org/docs/getting-started.html#docker
Support for SAML and OIDC
E2e testing seems possible
IAM supported, unclear if SSO is natively supported
Adequate documentation and support

### 7. Auth0
Paid but there's a free tier
Not open source (SAAS)
Didn't bother to check on the other features

**Comment by rmayore** [comment]
@mrjones-plip @raphaelkenyuri most of the options above support user federation, allowing syncing of identities from other LDAP or AD systems, therefore precluding the need to consider AD itself as an option. Instead keycloak (as an example) can be set up to sync identities from Azure AD.

**Comment by rmayore** [comment]
### Recommendation

cc @mrjones-plip @jkuester 

I recommend we pick **Keycloak** because of the following reasons:
- It's free to use both for development and for production environments.
- It's Open-source.
- Easy setup for development (docker), and at a glance easy setup for prod environments using either docker compose or K8S. This means it could be included at some point in the CHT services deployed (docker compose or k8s). Also this fact makes it easy to transition it from dev to prod.
-  Can be set up in a highly available way.
- On top of Identity Management, External users from other ADs can be managed
- Social sign-in can be supported (Google, twitter, facebook, etc)
- Admin management console, User management console
- Support for all common protocols
- Is a CNCF project, if that carries any weight

**Comment by rmayore** [comment]
I'll try to write some E2E tests against Keycloak, so we can cross that off.

**Comment by mrjones-plip** [comment]
excellent research and great transparency on your process - thank you @rmayore ! I would say do what ever testing (either manual setting up of docker or nascent e2e tests) and once you feel confident in your choice - write up some docs (just on this ticket is a good place to start) on how to set up a development environment.  Keep to just the simplest of steps covering just the  happy path.

w00t!

**Comment by jkuester** [comment]
Thanks for the great write-up @rmayore!  KeyCloak seems like a solid choice for using during development. I like how it gives a nice web GUI for configuring services/users/etc.  

If anyone has a basic docker compose config for spinning up KeyCloak locally that they could share here, that would be great!

**Comment by mrjones-plip** [comment]
maybe need TLS in dev?  [Local-IP certs](https://local-ip.medicmobile.org/) might be handy! These work on any local IP on a LAN and offer an easy way to `curl` in place the private keys

**Comment by rmayore** [comment]
### Setup
@mrjones-plip you can spin up keycloak locally with the below docker command:

`docker run -p 8080:8080 -e KC_BOOTSTRAP_ADMIN_USERNAME=admin -e KC_BOOTSTRAP_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:26.1.1 start-dev`

Optionally, you can put this into a docker compose file:
services:
```
  keycloak_web:
    image: quay.io/keycloak/keycloak:26.1.1
    container_name: keycloak_web
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password

      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: "${KEYCLOAK_ADMIN:-admin}"
      KEYCLOAK_ADMIN_PASSWORD: "${KEYCLOAK_ADMIN_PASSWORD:-admin}"
    command: start-dev
    depends_on:
      - keycloakdb
    ports:
      - 8080:8080

  keycloakdb:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

volumes:
  postgres_data:
```
The start it with 
`KEYCLOAK_ADMIN=admin1 KEYCLOAK_ADMIN_PASSWORD=password1 docker compose -f keycloak-docker-compose.yml up -d`


### Access
http://localhost:8080/admin
